### ISSUE TITLE
Begining block is wrong

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter-currency-monit#67]
https://g1-monit.elois.org/membersCount?lg=fr&begin=0&end=52993&step=1&stepUnit=days&nbMaxPoints=150&adaptMaxPoints=begin

Starting from block 0 make it start at block 11728.

**Comment by M5oul** [comment]
It seems a too long period can't be chosen.

**Comment by librelois** [comment]
This is normal behavior linked to a new feature of version 0.4.5 :

The maximum number of points is limited to 150 by default, and if you request an interval that contains more than 150 points then the begin parameter is automatically adjusted so that the interval is 150 points long.

You can change this behaviour by changing the maximum number of points to display (`nbMaxPoints`), or by modifying the parameter to adapt (`adaptMaxPoints`).
